name: Launch and SSH into EC2 Instance (copy web-us11)

on:
  push:
    branches:
      - release-aws  # Trigger the workflow on a push to the main branch

env:
  AWS_REGION: us-east-2 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Debug AWS Access Key ID
      run: |
        echo "Hash of AWS_ACCESS_KEY_ID: $(echo -n ${{ secrets.AWS_ACCESS_KEY_ID }} | sha256sum)"