name: Launch and SSH into EC2 Instance 

on:
  push:
    branches:
      - release-aws  # Trigger the workflow on a push to the main branch

env:
  AWS_REGION: us-east-2 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get AWS Account ID
      id: check-account-id
      run: |
        echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

    - name: Display Account ID
      id: display-account-id
      run: |
        modified_id="ID: ${ACCOUNT_ID}"
        echo $modified_id

